id: I1349E911
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T19:38:47+00:00'
last_modified: '2022-06-08T06:46:49.534562+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23783
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ནང་སྒྲུབ་རིག་འཛིན་འདུས་པའི་ཟིན་བྲིས་རིག་འཛིན་ཞལ་ལུང་བདེ་ཆེན་དཔལ་སྟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    422A:
      image_group_id: I2762
      title: ''
      total_pages: 642
      order: 1
      base_file: 422A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
