id: P006776
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23783
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ནང་སྒྲུབ་རིག་འཛིན་འདུས་པའི་ཟིན་བྲིས་རིག་འཛིན་ཞལ་ལུང་བདེ་ཆེན་དཔལ་སྟེར
  author: ''
  volumes:
    b4bd0e62b6f34324913d25316f1e19dd:
      image_group_id: I2762
      title: ''
      volume_number: 1
      total_pages: 642
      base_file: v001.txt
