id: opecha:P006776
initial_creation_type: ocr
source_metadata:
  id: bdr:W23783
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ནང་སྒྲུབ་རིག་འཛིན་འདུས་པའི་ཟིན་བྲིས་རིག་འཛིན་ཞལ་ལུང་བདེ་ཆེན་དཔལ་སྟེར
  volume: ''
  author: ''
